# Generated by Django 5.2.9 on 2026-01-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
